In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"D:\Machine Learning 100 days\Day_74_Naive_bayes\play_tennis.csv")

In [3]:
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [6]:
df.drop(columns=['day'],inplace=True)

In [9]:
df.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [10]:
#Problem 1

#outlook=sunny, temp=hot, humidity=high, wind=weak
#play or not play?

In [11]:
#solution 1

#P(Yes | sunny,hot,high,weak)=P(sunny | yes) * P(hot | yes) * P(high | yes) * P(weak | yes) * P(yes)
#P(No | sunny,hot,high,weak)=P(sunny | no) * P(hot | no) * P(high | no) * P(weak | no) * P(no)

#compare and decide using the maximum a posterios rule

In [12]:
#Problem 2

#outlook=overcast, temp=cold, humidity=low, wind=weak
#play or not play?

In [13]:
#solution 2

# change accordingly

#compare and decide using the maximum a posterios rule

In [14]:
#Any machine learning algorithm works in two phases training and testing phase

#so in training state Naive bayes creates a loopup table and stores in dictionary like stores all the possible possiblities

In [15]:
#let's find probability 

#P(Yes)
#P(No)

In [17]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [28]:
pyes = 9/14
pno = 5/14

In [30]:
print(pyes)
print(pno)

0.6428571428571429
0.35714285714285715

In [31]:
#Outlook column
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [32]:
POvercastNo=0
PRainNo=2/5
PSunnyNo=3/5

POvercastYes=4/9
PRainYes=3/9
PSunnyYes=2/9

In [33]:
#temp column
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [34]:
PCoolNo=1/5
PHotNo=2/5
PMildNo=2/5

PCoolYes=3/9
PHotYes=2/9
PMildYes=4/9

In [35]:
#humidity column
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [36]:
PHighNo=4/5
PNormalNo=1/5

PHighYes=3/9
PNormalYes=6/9

In [37]:
#wind column
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [38]:
PStrongNo=3/5
PWeakNo=2/5

PStringYes=3/9
PWeakYes=6/9
#till here our look up table is ready

In [41]:
#outlook=sunny, temp=hot, humidity=high, wind=weak
#play or not play?
PPlay = pyes * PSunnyYes * PHotYes * PHighYes * PWeakYes
print(PPlay)

PNotPlay = pno * PSunnyNo * PHotNo * PHighNo * PWeakNo
print(PNotPlay)

0.007054673721340388
0.02742857142857143

In [ ]:
#so this will not play bcoz it have the more probability